# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W2dp1EyYIaeVf6fIvJOBHMTfR51kjQvs
"""

import streamlit as st
import numpy as np
from prediction import predict

def main():
    st.title("Deepfake Prediction App")
    st.write("Upload an audio file to predict whether it's a deepfake or not.")

    # File upload
    file = st.file_uploader("Upload Audio File", type=['wav'])

    if file is not None:
        # Perform prediction
        predictions = predict(file)

        # Display result
        if predictions == 0:
            st.write("The audio is classified as AI voice.")
        else:
            st.write("The audio is classified as human voice.")

if __name__ == "__main__":
    main()