# -*- coding: utf-8 -*-
"""feature_extraction

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jJQEnr_VOPUcAJxOQNA1iR5F5U62ZCLJ
"""

import tensorflow as tf

def audio_to_fft(audio):
    audio = tf.squeeze(audio, axis=-1)
    fft = tf.signal.fft(tf.cast(tf.complex(real=audio, imag=tf.zeros_like(audio)), tf.complex64))
    fft = tf.expand_dims(fft, axis=-1)
    return tf.math.abs(fft[:, : (audio.shape[1] // 2), :])